### ISSUE TITLE
PagarMe::ConnectionError: PagarMe::ConnectionError - Error connecting to server: connection refused

### ISSUE THREAD

**Issue by kiromba** [pagarme/pagarme-ruby#16]
Não estou conseguindo utilizar essa biblioteca. Testando via cURL, consigo acesso e resposta do servidor normalmente, mas quando vou utilizar em Ruby, o erro que está no título é retornado.

from vendor/bundle/ruby/2.2.0/gems/pagarme-1.9.9/lib/pagarme/request.rb:64:in `run'
from /vendor/bundle/ruby/2.2.0/gems/pagarme-1.9.9/lib/pagarme/model.rb:36:in `find_by_id'

Isso acontece pra qualquer ação que eu tente fazer, como consultas, transações, planos e etc.

**Comment by kiromba** [comment]
Bom, encontrei o problema. O MAC não encontrava o arquivo correto(".pem") para poder fazer requisições usando SSL. 

Essa gem resolveu o problema. 

https://rubygems.org/gems/certified

**Comment by cirdes** [comment]
Eu me deparei com o mesmo problema, infelizmente essa gem não resolveu aqui.

**Comment by thebergamo** [comment]
@cirdes você consegue pingar o `api.pagar.me`?

**Comment by kiromba** [comment]
@cirdes esse problema só dava no meu computador(ambiente dev), em produção(LINUX) funciona corretamente. Então se a gem não resolver, vc pode ir direto na biblioteca do pagar.me, no arquivo request.rb e na linha 36, quando é feita a requisição via REST, vc pode acrescentar o parâmetro :verify_ssl => false. 

Outros links para resolver de vez o problema:
http://railsapps.github.io/openssl-certificate-verify-failed.html
https://gist.github.com/luislavena/f064211759ee0f806c88

**Comment by cirdes** [comment]
@thebergamo e @kiromba, obrigado pela ajuda. Na última versão da gem não tive mais esse problema.
