### ISSUE TITLE
Concerns over the quality and life of this gem.

### ISSUE THREAD

**Issue by abitdodgy** [pagarme/pagarme-ruby#27]
There are many outstanding pull requests, and the gem has a number of issues. More importantly it doesn't seen to be getting any attention. The code quality in general does not inspire confidence. The Ruby is not very idiomatic, and the code formatting is all over the place. There are a lot of missing features as well. It just seems to be half-baked, or--with all due respect--written by someone who isn't very familiar with Ruby.

Any time you issue a call to `PagarMe::Transaction.find_by_id` or `PagarMe::Subscription.find_by_id` and the `id` is `nil` or `blank` the entire resource collection is returned instead of an error.

```ruby
PagarMe::Subscription.find_by_id(nil) #=> All subscriptions are returned
PagarMe::Transaction.find_by_id(" ")  #=> All transactions are returned
```

It's also missing the ability to return all transactions by subscription id, and instead we have to issue a seprate API call using HTTParty....

Has development on this stopped?

**Comment by dalthon** [comment]
Development on this gem is not stopped.

We know that it was a little delayed and not in sync with all features that our API currently have.

We will cover our API asap.

About the find_by_id bug, is now fixed. Thanks to report it.

About getting all transactions by subscription_id, it was possible to get it using method find_by_hash:

```ruby
  PagarMe::Transaction.find_by_hash subscription_id: subscription.id
```

We understand that maybe it was ambiguous, so now we added an alias, find_by that works exactly the same way

```ruby
  PagarMe::Transaction.find_by subscription_id: subscription.id
```

We will continue to support this gem, and we promise that we will take care of it better.
