### ISSUE TITLE
Documentação incompleta

### ISSUE THREAD

**Issue by diogors** [pagarme/pagarme-ruby#43]
Favor completar a documentação Ruby em: https://docs.pagar.me/api/?ruby#retornando-todos-os-recebedores

**Comment by guilhermedallanol** [comment]
Acredito que a documentação esteja meio desatualizada mesmo. 

Há previsão pra atualização?

**Comment by dalthon** [comment]
Atualizado esse ponto das docs!

Vlw pelo toque!
