### ISSUE TITLE
Split rule em pagamentos com checkout

### ISSUE THREAD

**Issue by jmbrito01** [pagarme/pagarme-ruby#49]
Olá, uso o checkout com javascript no meu sistema de pagamento e agora quero adicionar o split rule sem ter que mudar todo o sistema de pagamento, existe algum jeito de usar o checkout com o split rule? Na documentação não explica nada sobre isso.

Obrigado.

**Comment by grvcoelho** [comment]
Oi @jmbrito01, tudo bem?

Não há como criar splitRules via checkout. Esta regra de negócio tem que ser feita do lado do servidor (back-end) mesmo.

Qualquer dúvida é só reabrir a issue :wink:
