### ISSUE TITLE
Refund receipt

### ISSUE THREAD

**Issue by jmbrito01** [pagarme/pagarme-ruby#53]
Is there some way to retrieve the refund receipt from a transaction from the api?

**Comment by vagnervst** [comment]
Hi @jmbrito01 I am Vagner, member of the Pagar.me's Tech Support team. 

There isn't a route to retrieve receipts, instead, you can filter by `status = refunded` using the `/transactions` route.

You can get more info [here](https://docs.pagar.me/reference#retornando-transa%C3%A7%C3%B5es).

Vagner S
