### ISSUE TITLE
The sample in the README does not work.

### ISSUE THREAD

**Issue by gilderlan** [pagarme/pagarme-ruby#63]
If I execute
```
transaction = PagarMe::Transaction.new(
    amount:         1000,    # in cents
    payment_method: 'boleto'
)
transaction.charge
```

I get the error:
```
PagarMe::ValidationError: "value" is required
```

**Comment by murilohns** [comment]
Hello @gilderlan,

You must use a payload like that:
```
transaction = PagarMe::Transaction.new(
    amount:         1000,    # in cents
    payment_method: 'boleto',
    documents: [
        {
           type: 'cpf',
           number: '00000000000'
        }
    ]
)
transaction.charge
```
You must follow this reference docs to use Pagar.me in your current API version: https://docs.pagar.me/v2017-08-28

Best regards.

**Comment by cenouro** [comment]
Getting the same error as @gilderlan. And the same error again if I run the code provided by @murilohns.

Also, the documentation link is broken. Can you provide some direction? It really seems the documentation for this gem is outdated.

Best regardss.

**Comment by murilohns** [comment]
Hello @cenouro, you can access the updated documentation in the following link: https://docs.pagar.me/reference

**Comment by giovanisleite** [comment]
Versão da API: 2017-08-28

![Screen Shot 2019-03-18 at 13 06 43](https://user-images.githubusercontent.com/11703235/54544613-cc12c580-497e-11e9-9a8a-788de3fb25f7.png)

```
PagarMe::Transaction.new(
  async: false,
  soft_descriptor: 'Foobar Payment',
  amount: 10000, # in cents
  card_hash: card_hash,
  payment_method: 'credit_card',
).charge
```

Mesmo erro
```
PagarMe::ValidationError ("value" is required)
```

**Comment by jnettome** [comment]
Has someone managed how to fix that? I'm facing the same issue with credit card. `value` is required.
