### ISSUE TITLE
Meio de Pagamento PIX

### ISSUE THREAD

**Issue by muriloime** [pagarme/pagarme-ruby#81]
Olá, é possível utilizarmos o meio de pagamento PIX por esta gem? Notei que na biblioteca Java já é possível. Para nós é mega importante que seja possível. Desde já obrigado

**Comment by derickhoganpimenta** [comment]
Também quero acompanhar isso.

**Comment by fabioaraujo121** [comment]
Essa gem é bem flexível. @kelvinromero percebeu que é só colocar o` payment_method: 'pix'` e passar os params 
```ruby
     {
        amount:  args[:amount].to_s.gsub(/[.,]/, '').to_i, # amount_cents
        payment_method: 'pix',
        expires_in: 60 * 5, # expires_in_seconds
        pix_expiration_date: 2.days.from_now
      }
```

Mas essa funcionalidade ainda não tá disponível em Development. Só subindo pra produção pra ver funcionar.

**Comment by muriloime** [comment]
fechando
